[package]
name = "checkLinks"
version = "0.1.0"
authors = ["Hugo <hchastel@laposte.net>"]
edition = "2018"

[dependencies]
lazy_static = "1.2.0"
regex = "1"
reqwest = "0.9.18"
prettytable-rs = "^0.8"
